---
name: Config-Model-OpenSsh
version: 1.204
author:
  - Dominique Dumont (ddumont at cpan dot org)
abstract: OpenSsh configuration files editor
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
requires:
  Config::Model: 0.632
  Log::Log4perl: 0
  perl: 5.8.0
recommends:
  Config::Model::Backend::Augeas: 0
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
provides:
  Config::Model::OpenSsh:
    file: lib/Config/Model/OpenSsh.pm
    version: 1.204
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
