---
abstract: 'OpenSsh config editor'
author:
  - 'Dominique Dumont'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::Warn: 0.11
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-OpenSsh
recommends:
  Config::Model::Backend::Augeas: 0
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
requires:
  Config::Model: 1.234
  Log::Log4perl: 1.11
version: 1.212
