---
abstract: 'OpenSSH config editor'
author:
  - 'Dominique Dumont'
build_requires:
  AnyEvent: 0
  Config::Model::Tester: 2.042
  EV: 0
  Module::Build: 0.3601
  Test::More: 0
  Tk: 0
configure_requires:
  Config::Model: 2.041
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-OpenSsh
recommends:
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
requires:
  Config::Model: 2.041
  File::HomeDir: 0
  Log::Log4perl: 1.11
  Mouse: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model-OpenSsh
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model-openssh.git
version: 1.231
