---
abstract: 'OpenSsh configuration files graphical editor'
author:
  - 'Dominique Dumont (ddumont at cpan dot org)'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-OpenSsh
provides:
  Config::Model::OpenSsh:
    file: lib/Config/Model/OpenSsh.pm
    version: 1.210
recommends:
  Config::Model::Backend::Augeas: 0
  Config::Model::CursesUI: 0
  Config::Model::TkUI: 0
requires:
  Config::Model: 0.637
  Log::Log4perl: 0
  Parse::RecDescent: 0
  perl: v5.8.0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 1.210
