=head1 NAME

Config::Model::models::Sshd::MatchCondition - Configuration class Sshd::MatchCondition

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

Conidtion to apply to identify matched items inside 
a sshd_config match block.

=head1 Elements

=head2 C<User>

Define the User criteria of a conditional block. The value of this field is a pattern that is tested against user name.Optional. Type uniline.

=head2 C<Group>

Define the Group criteria of a conditional block. The value of this field is a pattern that is tested against group name.Optional. Type uniline.

=head2 C<Host>

Define the Host criteria of a conditional block. The value of this field is a pattern that is tested against host name.Optional. Type uniline.

=head2 C<Address>

Define the Address criteria of a conditional block. The value of this field is a pattern that is tested against the address of the incoming connection.Optional. Type uniline.

=head1 SEE ALSO

=over

=item L<config-edit>

=back

=head1 AUTHOR

=over

=item ARRAY(0x3d99ea8)


=back

=head1 COPYRIGHT

=over

=item ARRAY(0x3d971b0)


=back

=head1 LICENSE

=over

=item LGPL2


=back

=cut

